# Generated by Django 5.1.2 on 2025-01-24

import uuid
from django.db import migrations, models


def populate_unique_uids(apps, schema_editor):
    CV = apps.get_model('candidates', 'CV')
    for cv in CV.objects.all():
        cv.uid = uuid.uuid4()
        cv.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0045_remove_jobsearch_candidate_jobsearch_cv_and_more'),
    ]

    operations = [
        # Step 1: Add the uid field without constraints
        migrations.AddField(
            model_name='cv',
            name='uid',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        # Step 2: Populate unique uids for existing records
        migrations.RunPython(populate_unique_uids, migrations.RunPython.noop),
        # Step 3: Add unique constraint and make the field non-nullable
        migrations.AlterField(
            model_name='cv',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
