# Generated by Django 5.1.2 on 2025-01-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0046_cv_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
