# Generated by Django 5.1.2 on 2025-02-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0047_jobsearch_last_scored_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(db_index=True, help_text='Unique identifier for linking translations. Choose an existing one or create a new one.', max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(help_text='Unique identifier to group translations of the same career title.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='credits_to_start_with',
            field=models.PositiveIntegerField(default=0, help_text='Number of credits to start with'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='candidates.answerset')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='candidates.candidate')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidates.career')),
            ],
        ),
        migrations.AddField(
            model_name='answerset',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sets', to='candidates.language'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(db_index=True, help_text='Unique identifier for linking translations. Choose an existing one or create a new one.', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('answer_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='candidates.answerset')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='candidates.language')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='candidates.candidate')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='candidates.answeroption')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='multi_responses', to='candidates.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='candidates.question')),
            ],
        ),
        migrations.CreateModel(
            name='CareerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transition_path', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='candidates.career')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_translations', to='candidates.language')),
            ],
            options={
                'unique_together': {('career', 'language')},
            },
        ),
    ]
