# Generated by Django 5.1.2 on 2025-02-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0048_answerset_career_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='group_identifier',
        ),
    ]
