# Generated by Django 5.1.2 on 2025-01-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0048_answerset_language_questioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='candidates.answerset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
