# Generated by Django 5.1.2 on 2025-02-16 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0049_remove_answerset_group_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tailored_cvs', to='candidates.career'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='credits_to_start_with',
            field=models.PositiveIntegerField(default=0, help_text='Number of credits to start with'),
        ),
    ]
