# Generated by Django 5.1.2 on 2025-01-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0049_question_answer_set_alter_question_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='group_identifier',
            field=models.CharField(db_index=True, default=None, help_text='Unique identifier for linking translations. Choose an existing one or create a new one.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='group_identifier',
            field=models.CharField(db_index=True, default=None, help_text='Unique identifier for linking translations. Choose an existing one or create a new one.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='candidates.answerset'),
        ),
    ]
