# Generated by Django 5.1.2 on 2025-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0050_cv_career_generalsetting_credits_to_start_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='num_of_careers_to_generate',
            field=models.PositiveIntegerField(default=5, help_text='Number of careers to generate'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='credits_to_start_with',
            field=models.PositiveIntegerField(default=10, help_text='Number of credits to start with'),
        ),
    ]
