# Generated by Django 5.1.2 on 2025-02-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0050_answerset_group_identifier_question_group_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='value',
        ),
        migrations.RemoveField(
            model_name='answerset',
            name='usage_count',
        ),
    ]
