# Generated by Django 5.1.2 on 2025-02-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0051_remove_answeroption_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='question',
            name='identifier',
        ),
    ]
