# Generated by Django 5.1.2 on 2025-02-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0053_candidateresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
