# Generated by Django 5.1.2 on 2025-02-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0054_delete_questioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(help_text='Unique identifier to group translations of the same career title.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='candidates.candidate')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidates.career')),
            ],
        ),
        migrations.CreateModel(
            name='CareerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transition_path', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='candidates.career')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_translations', to='candidates.language')),
            ],
            options={
                'unique_together': {('career', 'language')},
            },
        ),
    ]
